spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kotlin-spring-db
    username: GudvinZ
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop



